# Generated by Django 4.2.18 on 2026-06-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricantes',
            fields=[
                ('codigo', models.AutoField(help_text='Código do fabricante', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome do fabricante', max_length=70)),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
                'db_table': 'fabricante',
            },
        ),
    ]
