# Generated by Django 4.2.18 on 2026-06-19 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabricantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabricantes',
            options={},
        ),
        migrations.AlterModelTable(
            name='fabricantes',
            table=None,
        ),
    ]
