# Generated by Django 4.2.18 on 2026-06-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabricantes', '0002_alter_fabricantes_options_alter_fabricantes_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabricantes',
            options={'verbose_name': 'Fabricantes', 'verbose_name_plural': 'Fabricantes'},
        ),
    ]
